[general]
id = "br1-ff00_0_122-1"
config_dir = "topos/default/ASff00_0_122"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:21]:30442"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:21]:31142"

[log.console]
level = "debug"
