[general]
id = "cs1-ff00_0_122-1"
config_dir = "topos/default/ASff00_0_122"

[trust_db]
connection = "gen-cache/cs1-ff00_0_122-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_122-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_122-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:23]:30452"

[api]
addr = "[fd00:f00d:cafe::7f00:23]:31152"

[features]

[log.console]
level = "debug"

[drkey.level1_db]
connection = "gen-cache/cs1-ff00_0_122-1.drkey_level1.db"

[drkey.secret_value_db]
connection = "gen-cache/cs1-ff00_0_122-1.secret_value.db"
