[general]
id = "br2-ff00_0_211-1"
config_dir = "topos/default/ASff00_0_211"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:39]:30442"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:39]:31142"

[log.console]
level = "debug"
