[general]
id = "br2-ff00_0_222-2"
config_dir = "topos/default/ASff00_0_222"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:52]:30442"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:52]:31142"

[log.console]
level = "debug"
