[general]
id = "cs2-ff00_0_222-1"
config_dir = "topos/default/ASff00_0_222"

[trust_db]
connection = "gen-cache/cs2-ff00_0_222-1.trust.db"

[beacon_db]
connection = "gen-cache/cs2-ff00_0_222-1.beacon.db"

[path_db]
connection = "gen-cache/cs2-ff00_0_222-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:53]:30452"

[api]
addr = "[fd00:f00d:cafe::7f00:53]:31152"

[features]

[log.console]
level = "debug"
