[general]
id = "sd2-ff00_0_222"
config_dir = "topos/default/ASff00_0_222"

[trust_db]
connection = "gen-cache/sd2-ff00_0_222.trust.db"

[path_db]
connection = "gen-cache/sd2-ff00_0_222.path.db"

[sd]
address = "[fd00:f00d:cafe::7f00:54]:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:54]:30455"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:54]:30955"

[drkey_level2_db]
connection = "gen-cache/sd2-ff00_0_222.drkey_level2.db"

[log.console]
level = "debug"
