[general]
id = "br1-ff00_0_111-3"
config_dir = "topos/default/ASff00_0_111"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:1b]:30442"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:1b]:31142"

[log.console]
level = "debug"
