[general]
id = "br1-ff00_0_110-3"
config_dir = "topos/default/ASff00_0_110"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:13]:30442"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:13]:31142"

[log.console]
level = "debug"
