[general]
id = "cs1-ff00_0_110-1"
config_dir = "topos/default/ASff00_0_110"

[trust_db]
connection = "gen-cache/cs1-ff00_0_110-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_110-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_110-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:14]:30452"

[api]
addr = "[fd00:f00d:cafe::7f00:14]:31152"

[features]

[ca]
mode = "in-process"

[log.console]
level = "debug"
