[general]
id = "sd1-ff00_0_110"
config_dir = "topos/default/ASff00_0_110"

[trust_db]
connection = "gen-cache/sd1-ff00_0_110.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_110.path.db"

[sd]
address = "127.0.0.69:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "127.0.0.69:30455"

[features]

[api]
addr = "127.0.0.69:30955"

[log.console]
level = "debug"
