[general]
id = "sd1-ff00_0_110"
config_dir = "topos/default/ASff00_0_110"

[trust_db]
connection = "gen-cache/sd1-ff00_0_110.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_110.path.db"

[sd]
address = "[fd00:f00d:cafe::7f00:15]:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:15]:30455"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:15]:30955"

[drkey_level2_db]
connection = "gen-cache/sd1-ff00_0_110.drkey_level2.db"

[log.console]
level = "debug"
