[general]
id = "cs1-ff00_0_112-1"
config_dir = "topos/tiny4/ASff00_0_112"

[trust_db]
connection = "gen-cache/cs1-ff00_0_112-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_112-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_112-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "127.0.0.26:30452"

[api]
addr = "127.0.0.26:31152"

[features]

[log.console]
level = "debug"
