[general]
id = "sd2-ff00_0_210"
config_dir = "topos/default/ASff00_0_210"

[trust_db]
connection = "gen-cache/sd2-ff00_0_210.trust.db"

[path_db]
connection = "gen-cache/sd2-ff00_0_210.path.db"

[sd]
address = "127.0.0.166:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "127.0.0.166:30455"

[features]

[api]
addr = "127.0.0.166:30955"

[log.console]
level = "debug"
