[general]
id = "br2-ff00_0_220-4"
config_dir = "topos/default/ASff00_0_220"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:44]:30442"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:44]:31142"

[log.console]
level = "debug"
