[general]
id = "sd2-ff00_0_220"
config_dir = "topos/default/ASff00_0_220"

[trust_db]
connection = "gen-cache/sd2-ff00_0_220.trust.db"

[path_db]
connection = "gen-cache/sd2-ff00_0_220.path.db"

[sd]
address = "[fd00:f00d:cafe::7f00:46]:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:46]:30455"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:46]:30955"

[log.console]
level = "debug"
