[general]
id = "br1-ff00_0_130-2"
config_dir = "topos/default/ASff00_0_130"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:2a]:30442"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:2a]:31142"

[log.console]
level = "debug"
