[general]
id = "sd1-ff00_0_130"
config_dir = "topos/default/ASff00_0_130"

[trust_db]
connection = "gen-cache/sd1-ff00_0_130.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_130.path.db"

[sd]
address = "[fd00:f00d:cafe::7f00:2c]:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:2c]:30455"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:2c]:30955"

[log.console]
level = "debug"
