[general]
id = "sd1-ff00_0_111"
config_dir = "topos/tiny4/ASff00_0_111"

[trust_db]
connection = "gen-cache/sd1-ff00_0_111.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_111.path.db"

[sd]
address = "127.0.0.19:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "127.0.0.19:30455"

[features]

[api]
addr = "127.0.0.19:30955"

[log.console]
level = "debug"
