[general]
id = "sd1-ff00_0_112"
config_dir = "topos/default/ASff00_0_112"

[trust_db]
connection = "gen-cache/sd1-ff00_0_112.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_112.path.db"

[sd]
address = "127.0.0.60:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "127.0.0.60:30455"

[features]

[api]
addr = "127.0.0.60:30955"

[drkey_level2_db]
connection = "gen-cache/sd1-ff00_0_112.drkey_level2.db"

[log.console]
level = "debug"
